name: Check for deadlinks in markdown files

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 */6 * * *"
    workflow_dispatch:

jobs:
  markdown-deadlink-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'